services:
  app:
    build: .
    container_name: jukebox
    restart: unless-stopped
    depends_on:
      - bgutil-provider
    env_file: .env.prod
    environment:
      SQLITE_PATH: /data/jukebox.db
      MIGRATION: false
    volumes:
      - data:/data
    networks:
      - app-network

  bgutil-provider:
    image: brainicism/bgutil-ytdlp-pot-provider
    container_name: bgutil-provider
    restart: unless-stopped
    init: true
    ports:
      - "4416:4416"
    networks:
      - app-network

volumes:
  data:

networks:
  app-network:
